# Generated by Django 3.2.16 on 2022-12-25 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_info', models.TextField()),
                ('appointment_type', models.IntegerField(choices=[(1, 'Haircut'), (2, 'Beard Grooming'), (3, 'Haircut & Beard')], default=1)),
                ('appointment_time', models.DateField()),
                ('slots', models.IntegerField(choices=[(12, '12:00'), (17, '17:00'), (13, '13:00'), (18, '18:00'), (16, '16:00'), (14, '14:00'), (15, '15:00'), (10, '10:00'), (11, '11:00')], default='10')),
                ('is_booked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-appointment_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('appointment_time', 'slots'), name='no_double_booking'),
        ),
    ]
