# Generated by Django 3.2.16 on 2022-12-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slots',
            field=models.IntegerField(choices=[(12, '12:00'), (11, '11:00'), (16, '16:00'), (13, '13:00'), (18, '18:00'), (17, '17:00'), (10, '10:00'), (15, '15:00'), (14, '14:00')], default='10'),
        ),
    ]
